### ISSUE TITLE
How do I use mean_and_std_of_dataset.txt without running the full pipeline?

### ISSUE THREAD

**Issue by olsonday** [JacobHanimann/scDINO#2]
Thank you so much for writing scDINO-it will be of great use to my work on cell morphology! I am currently trying to run the downstream pipeline using the pre-trained scDINO model, and I am unsure of what file to include for the “ mean_std_file_location”. I noticed that a mean_and_std_of_dataset.txt file appears to be an output of the full pipeline. Is there a way to access this file without running the full pipeline? I also could set “parse_mean_std_from_file” to False while computing cls features, but I am unsure how or if this would affect the overall function. Thank you so much for any insights.

**Comment by JacobHanimann** [comment]
Thank you for your interest in scDINO! Currently, the output mean_and_std_of_dataset.txt file is not on the repo. The mean and standard deviation values in that file represent per-channel statistics of the training image dataset. Since the "scDINO model" was trained on the immune cells dataset mentioned in the readme, you can find these values in the arguments file (.github/scDINO_args.txt). The values should be 'norm_per_channel': '[(0.2981, 0.5047, 0.1918, 0.2809, 0.3800),(0.2232, 0.1659, 0.2403, 0.1938, 0.1956)]'. You should be able to include these values in the configuration file and set the "parse_mean_std_from_file" to False. I hope this works for you!

**Comment by olsonday** [comment]
Thank you so much! That seems to work!
