### ISSUE TITLE
Question about downstream run yaml config file

### ISSUE THREAD

**Issue by MikeLippincott** [JacobHanimann/scDINO#7]
Hi Jacob,

First, thank you for your work on scDINO. I have been using it for some of my analysis looking into cell death!

I had some questions about the parameters defined in the [only_downstream_analyses.yaml](configs/only_downstream_analyses.yaml) config file. 
I might have missed it but, I am having trouble understanding what all of the parameters are for and how to define them.
If I could get some clarification that would be amazing!
Some params in particular that I do not quite understand:
- `selected_channel_combination_per_run`
    - The default is ["01234", "0", "1", "2", "3", "4"]. Are certain channels run through the model alone??
- `norm_per_channel`
    - How would one go about calculating these normalization weights??
- `custom_embedding_map` the default is "{0:2, 1:2, 2:2, 3:2, 4:2}"
    - Using this embedding map outputs channels 0-4 to one embedding space?? Is this a correct interpretation??

If additional documentation should be added, I can help with a pull request.

Thank you for your help and for creating this amazing tool and model.

Best,
Mike

**Comment by JacobHanimann** [comment]
Hi Mike!

I'm happy to hear that you're using it! :-)

selected_channel_combination_per_run: Each element in the list represents a single run. In the first run, all 5 channels are used as input, and in the second run, only the first one is used. Each run produces its own results.

norm_per_channel: Please refer to issue #2 .

custom_embedding_map: Yes, it will result in one embedding space where each channel is embedded with the same convolution weights.

I wouldn't really recommend using the scDINO weights for anything other than analyzing the dataset it was trained on (the immune cells), because the model learned to interpret this specific staining panel. Instead, I would suggest using the Imagenet pretrained weights and embedding each grayscale channel separately (and combining them downstream), or transforming your grayscale images to RGB before inputting. In the best case scenario, you could (with enough images 10'000 <) train your own scDINO model with your own dataset and then use that for downstream analyses.

Feel free to write any documentation; I will accept the pull request right away.

Best, Jacob
